name: clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-tidy

    - name: apply_clang-tidy
      run: |
        clang-tidy $(find . -name "*.h" -or -name "*cc")
